/* Hướng dẫn sử dụng & thuật toán từng chức năng (có ví dụ tính trực tiếp từ dữ liệu) */
(function () {
  FS.pages.guide = { title: 'Hướng dẫn & Thuật toán', sub: 'Mỗi chức năng: dùng để làm gì, cách dùng từng bước, thuật toán/công thức bên trong', noFilter: true, render(root) {
    const I = FS.tables.incident_truth[0], R = FS.engine.impact(I), C = FS.config, n = FS.fmt.n, top = R.jts[0];
    const S = (id, t, purpose, how, algo, note) => `<details class="fx guide-s" ${id === 1 ? 'open' : ''}><summary>${t}</summary><h4>Dùng để làm gì</h4><p>${purpose}</p><h4>Cách dùng</h4><ol>${how.map(h => `<li>${h}</li>`).join('')}</ol><h4>Thuật toán / công thức</h4>${algo}${note ? `<h4>Lưu ý</h4><p>${note}</p>` : ''}</details>`;
    const sec = [
      S(1, '0 · Tổng quan & bộ lọc toàn cục', 'FlowSight nối các bảng rời rạc (sự cố, sản xuất, Lot, vật tư, JT/Order, giao hàng) thành chuỗi ảnh hưởng có thể kiểm chứng: Incident → Mất công suất → Thiếu sản lượng → Tồn kho/Vật tư → JT/Order → Giao hàng.',
        ['Đăng nhập (xem mục 13). Thanh lọc phía trên chọn khoảng ngày, máy/công đoạn, trạng thái sự cố, từ khóa — mọi KPI, biểu đồ, bảng đổi theo.', 'Ô tìm nhanh trên cùng: gõ <code>LOT-0403</code>, <code>INC-0001</code>, <code>JT-0231</code> hoặc mã máy rồi Enter để nhảy tới trang liên quan.', 'Nhãn <i>Đã xác nhận / Suy luận / Chưa đủ dữ liệu / Mô phỏng</i> cho biết độ chắc chắn của từng số liệu.'],
        '<p>Bộ lọc áp dụng lên <code>incident_truth.start_time</code>, <code>station_id</code>, trạng thái (suy ra từ <code>end_time</code> so với thời điểm hệ thống 10/10/2026 12:00, hoặc trạng thái người dùng ghi nhận). Các tổng hợp luôn đếm theo khóa duy nhất (<code>incident_id</code>, <code>jt_id</code>) nên không đếm trùng.</p>', 'Dữ liệu thiếu hiển thị "Chưa đủ dữ liệu", không tự thay bằng 0.'),
      S(2, '1 · Command Center (FR-01)', 'Cái nhìn nhanh về sự cố và ảnh hưởng sản xuất.', ['Xem 4 thẻ KPI; bấm vào KPI hoặc từng bước của chuỗi tác động để mở danh sách bản ghi tạo nên con số (có tìm kiếm, sắp xếp, xuất CSV).', 'Biểu đồ "Phân bổ nguyên nhân sự cố" có 4 tab: loại nguyên nhân, nhóm lỗi FMEA, máy/công đoạn, mức độ.', 'Khối "Danh mục & vật tư": tiêu thụ vật tư, tồn kho so với tồn an toàn, danh mục sản phẩm, lô vật tư nhận.', 'Khối "Hành động ưu tiên": tích vào hộp khi đã xử lý (cần quyền ghi nhận quyết định).'],
        `<div class="code">Sự cố trong kỳ   = |{incident_id : start_time ∈ [từ, đến], máy, trạng thái khớp}|
Sản lượng thực tế = Σ qty_out tại STN-PK ; Kế hoạch = Σ qty_in tại STN-PK
Thiếu ước tính  = Σ_sự cố thiếu hụt ròng (mục 3)
JT có nguy cơ   = |{jt_id : exposure > 0}| (đếm duy nhất giữa các sự cố)
Tiêu thụ vật tư = Σ qty_consumed theo component_id trong kỳ
Tồn so với an toàn: tồn snapshot COMPONENT mới nhất < safety_stock_qty ⇒ cảnh báo
Hành động ưu tiên = top 5 JT theo exposure + tối đa 2 sự cố thiếu liên kết Lot</div>`, 'Sản lượng kế hoạch lấy từ qty_in (lot đã phát hành) vì dữ liệu pilot không có kế hoạch riêng.'),
      S(3, '2 · Incident Monitoring (FR-02)', 'Quản lý sự cố — điểm bắt đầu của phân tích tác động.', ['Bấm một dòng để xem chi tiết: máy, mốc thời gian, FMEA, Lot liên quan, nguồn dữ liệu.', 'Đổi trạng thái (Đang mở / Đang xử lý / Đã đóng) rồi Lưu; lịch sử thay đổi hiển thị bên dưới.', 'Từ chi tiết bấm "Phân tích tác động" hoặc "Lan truyền" để đi tiếp.'],
        '<div class="code">Thời gian dừng = end_time − start_time (kiểm tra khớp duration_h, sai lệch > 0,01h ⇒ cảnh báo)\nSự cố chưa kết thúc ⇒ "Đang mở", không coi thời lượng hiện tại là thời lượng cuối\nCùng máy + cùng start_time nhưng khác incident_id ⇒ "cần đối soát", không tự cộng\nKhông có affected_lots ⇒ "Chưa đủ dữ liệu liên kết"</div>'),
      S(4, '3 · Impact Analysis (FR-03) — thuật toán chính', 'Ước tính sản lượng mất, thiếu hụt ròng, JT/Order và giao hàng có nguy cơ cho một sự cố, có thể what-if.', ['Chọn sự cố; sửa "Thời gian dừng" (what-if), lịch SX, % FG khả dụng, bật/tắt công suất bù; bấm "Tính lại".', 'Đọc 4 KPI, biểu đồ so sánh, chuỗi ảnh hưởng, bảng JT (bấm dòng để xem căn cứ liên kết).', 'Mở "Giả định & công thức" để tái lập từng bước.'],
        `<div class="code">B1  Giờ mất       = giờ dừng ∩ lịch SX (${C.schedStart}:00–${C.schedEnd}:00 mỗi ngày)   // không coi cả thời gian dừng là mất SL
B2  Mất lý thuyết = Giờ mất × công suất   (rated_rate_per_h; thiếu thì 3600 / cycle_time_s)
B3  FG khả dụng   = Σ FG snapshot gần nhất trước sự cố của các sản phẩm bị ảnh hưởng × ${C.fgUsablePct}%   // không cộng WIP
B4  Thiếu sau tồn = max(0, Mất lý thuyết − FG khả dụng)
B5  Bù / ngày     = spare_capacity_h_per_day × công suất
B6  Exposure JT   = min(SL JT, max(0, Thiếu sau tồn − Bù/ngày × (hạn giao − giờ kết thúc dừng)/24h))
B7  Thiếu ròng    = max exposure các JT   // cùng một thiếu hụt, không cộng trùng
Rủi ro = exposure/SL JT  ≥ ${C.thHigh}% Cao · ≥ ${C.thMid}% Trung bình · còn lại Thấp  (ngưỡng demo)</div>
<p><b>Ví dụ trực tiếp ${I.incident_id}</b> (${I.station_id}, ${I.duration_h}h): giờ mất ${n(R.lostH)}h × ${n(R.rate)} sp/h = <b>${n(R.lostQty)}</b> sp; FG khả dụng ${n(R.fgUsable)}; thiếu sau tồn ${n(R.deficit)}; bù/ngày ${n(R.perDay)}; thiếu ròng <b>${n(R.net)}</b> sp${top ? `; JT đầu bảng ${top.jt.jt_id} (${top.link}) exposure ${n(top.exposure)}` : ''}.</p>
<p>JT liên quan gồm <b>đã xác nhận</b> (qua khóa <code>jt_allocation_truth</code>: Lot bị ảnh hưởng → JT) và <b>suy luận</b> (quy tắc R-LINK-01: cùng line, hạn giao trong 72h sau sự cố).</p>`, 'Thiếu công suất ⇒ "Chưa đủ dữ liệu"; thiếu JT hoặc tồn kho ⇒ "Ước tính một phần". Không khẳng định giao trễ khi chưa có lịch giao.'),
      S(5, '4 · Propagation (FR-04)', 'Đồ thị lan truyền Incident → Máy → Lot → Vật tư/Lot con → JT → Giao hàng.', ['Chọn sự cố; bật/tắt từng loại quan hệ (trực tiếp / suy luận / chưa xác minh).', 'Bấm nút hoặc đường nối để xem thuộc tính, nguồn dữ liệu, căn cứ; bảng bên dưới liệt kê mọi liên kết.'],
        '<div class="code">Duyệt đồ thị theo khóa:\n incident.station_id → dim_station ;  incident.affected_lots → canonical_lots\n Lot → material_consumption (mat_lot) ; Lot → genealogy (SPLIT/MERGE) ; Lot → jt_allocation → JT → shipment\nQuan hệ: Trực tiếp (có khóa) · Suy luận (quy tắc) · Chưa xác minh (khóa không tìm thấy)\nKhông có affected_lots ⇒ nhánh "Chưa đủ dữ liệu liên kết" (không nối chỉ vì gần nhau về thời gian)</div>'),
      S(6, '5 · Lot Genealogy (FR-05)', 'Truy ngược nguồn gốc và truy xuôi đối tượng liên quan của một Lot.', ['Nhập Lot ID (gợi ý: LOT-0403, LOT-0404, LOT-2207) → Truy vết.', 'Bấm Lot trong bảng để đi tiếp; xem dòng thời gian công đoạn và kết quả QC; xuất danh sách.'],
        '<div class="code">Truy ngược: BFS theo parentOf (độ sâu ≤ 4) + vật tư tiêu thụ của Lot và của các Lot cha\nTruy xuôi: BFS theo childOf (độ sâu ≤ 4) + JT phân bổ + chuyến giao (nối qua JT)\nMức truy vết: Lot/Batch — không phải từng sản phẩm; quan hệ nối qua JT gắn nhãn "Suy luận"</div>'),
      S(7, '6 · Root Cause & Evidence (FR-08)', 'Gợi ý yếu tố liên quan và bằng chứng để kỹ sư đánh giá — không tự kết luận nhân quả.', ['Chọn sự cố; đọc bảng yếu tố, bằng chứng, độ tin cậy, trạng thái (Đã xác nhận / Giả thuyết).'],
        '<div class="code">Quy tắc nghiệp vụ + thống kê mô tả (chưa dùng ML):\n 1) FMEA của sự cố: hạng mục lỗi, RPN = S×O×D\n 2) Lô vật tư dùng chung bởi MỌI Lot bị ảnh hưởng ⇒ giả thuyết vật tư; độ tin cậy = tỷ lệ Lot dùng chung (×0,6 nếu nguồn không ghi là MATERIAL)\n 3) Số sự kiện bất thường vật lý trên các Lot liên quan\n 4) Tỷ lệ NG / phép đo QC của các Lot liên quan\nKhông đủ bằng chứng ⇒ "Chưa đủ bằng chứng để kết luận"</div>'),
      S(8, '7 · Ưu tiên & Hành động (FR-09)', 'Xếp thứ tự xử lý JT/Order và ghi nhận quyết định.', ['Xem bảng chỉ báo riêng từng JT; bấm dòng để xem lý do và chọn trạng thái (Chưa xem xét / Đang xem xét / Đã chấp nhận / Từ chối / Cần xác minh).', 'Tùy chọn bật "điểm tổng hợp" (trọng số demo, chỉnh ở Kiến trúc & Cấu hình).'],
        `<div class="code">Mặc định: sắp xếp theo thiếu hụt ước tính (không tạo điểm giả)\nĐiểm = Σ(w_i × x_i)/Σw_i × 100 ; x_i ∈ [0,1]:\n  thiếu hụt = min(1, exposure/SL) ; slack = 1 − slack_h/96 (≤0h ⇒ 1) ; liên kết = 1 (xác nhận) | 0,5 (suy luận)\n  lan truyền = min(1, số JT/10) ; tin cậy dữ liệu = 1 | 0,6 | 0,3\nTrọng số hiện tại: ${C.wShort}/${C.wSlack}/${C.wLink}/${C.wBreadth}/${C.wConf} (demo)</div>`, 'Hệ thống không gửi lệnh điều khiển máy hay đổi kế hoạch.'),
      S('7a', '7a · Phân bổ nguyên nhân sự cố', 'Phân tích chuyên sâu sự cố theo 4 góc nhìn: loại nguyên nhân, nhóm lỗi FMEA, máy/công đoạn, mức độ.',
        ['Bấm tab để đổi cách nhóm (Loại nguyên nhân / Nhóm lỗi FMEA / Máy / Mức độ); biểu đồ donut cập nhật theo.', 'Đọc bảng Top FMEA theo RPN để biết lỗi nào rủi ro nhất (RPN = S×O×D).', 'Bấm một dòng trong bảng chi tiết để nhảy sang Impact Analysis của sự cố đó.'],
        '<div class="code">Đếm incident_id duy nhất theo nhóm đã chọn (không đếm trùng)\nRPN hiển thị = max(RPN sự cố, RPN danh mục FMEA)\nTop FMEA: sắp xếp theo RPN giảm dần, lấy 8 đầu</div>',
        'Số liệu tuân theo bộ lọc toàn cục (ngày, máy, trạng thái).'),
      S('7b', '7b · Danh mục & vật tư', 'Theo dõi tiêu thụ vật tư, tồn kho so với tồn an toàn, lô vật tư nhận và danh mục sản phẩm.',
        ['Xem biểu đồ donut tiêu thụ vật tư trong kỳ (lọc theo ngày ở thanh trên).', 'Bảng tồn kho: thanh đỏ = dưới tồn an toàn, cần bổ sung; bấm để xem chi tiết.', 'Bảng lô vật tư: bấm một dòng để truy vết genealogy của lô vật tư đó.'],
        '<div class="code">Tiêu thụ = Σ qty_consumed theo component_id trong kỳ lọc\nTồn kho = snapshot COMPONENT mới nhất < safety_stock_qty ⇒ cảnh báo\nTỷ trọng = tiêu thụ loại / tổng tiêu thụ</div>',
        'Tồn kho là snapshot tại thời điểm dữ liệu, chưa trừ lượng đã phân bổ cho JT.'),
      S(9, '8 · Data Health (FR-07)', 'Đánh giá chất lượng dữ liệu trước khi phân tích.', ['Xem bảng theo từng bảng dữ liệu; bấm dòng để xem dòng lỗi (dòng, cột, nhóm lỗi); xuất báo cáo.', 'Bật điểm tổng hợp nếu muốn (trọng số demo).'],
        '<div class="code">Completeness = 1 − (ô bắt buộc trống / tổng ô bắt buộc)\nValidity     = 1 − (ngày giờ/số/giá trị ngoài miền không hợp lệ / ô được kiểm)\nUniqueness   = 1 − (khóa trùng / số dòng) — khóa theo đúng cấp dữ liệu (production: event_id; Lot ID lặp là hợp lệ)\nConsistency  = 1 − (dòng vi phạm quy tắc: duration_h ≠ end−start, qty_out > qty_in …)/số dòng\nReferential  = khóa ngoại tìm thấy / tổng khóa ngoại (affected_lots tách theo từng Lot)\nTimeliness   = số ngày từ bản ghi mới nhất đến thời điểm hệ thống</div>'),
      S(10, '9 · Validation Lab (FR-10)', 'So sánh kết quả engine với ground truth đã xác nhận.', ['Đọc từng ca (F01 tác động, R01 nguyên nhân): tham chiếu vs FlowSight, Khớp/Lệch.', 'Bấm "Lưu phiên bản kiểm chứng" để ghi lại cấu hình và kết quả.'],
        '<div class="code">Sai số = dự báo − thực tế ; APE = |sai số|/thực tế\nPrecision = TP / số JT engine báo ; Recall = TP / số JT tham chiếu ; Top-1 = nguyên nhân hàng đầu trùng tham chiếu</div>', 'Dữ liệu pilot chỉ xác nhận logic hệ thống, không chứng minh độ chính xác thực tế.'),
      S(11, '10 · Import & Data Mapping (FR-06)', 'Nhập CSV riêng theo nhóm, ánh xạ cột, kiểm tra trước khi đưa vào dữ liệu hoạt động.', ['Kéo-thả hoặc chọn CSV (UTF-8); kiểm tra nhóm dữ liệu tự nhận diện, sửa nếu sai.', 'Chỉnh ánh xạ cột nguồn → trường chuẩn; bấm "Kiểm tra dữ liệu"; xem lỗi theo dòng/cột.', '"Xác nhận nhập" chỉ đưa dòng hợp lệ vào bảng (upsert theo khóa); "Xuất CSV đã chuẩn hóa" để tải về. Dùng "Tạo tệp mẫu có lỗi" để thử.'],
        '<div class="code">Nhận diện nhóm: điểm = số trường chuẩn khớp tên cột (bỏ dấu/chữ hoa, có từ đồng nghĩa: "Mã lô"→lot_id, "Giá trị"→value) / (số trường bắt buộc + 2); chọn nhóm cao nhất nếu > 0,5\nKiểm tra: bắt buộc · kiểu số/ngày · miền giá trị · khóa trùng · khóa ngoại · quy tắc nhất quán\nTrạng thái: Chưa tải lên → Đang kiểm tra → Hợp lệ / Hợp lệ một phần / Không hợp lệ → Đã nhập</div>', 'Tệp gốc chỉ được đọc, không bị sửa. Cần quyền Nhập dữ liệu.'),
      S(12, '11 · Báo cáo & Xuất (FR-11)', 'Xuất CSV/Markdown có thời điểm, nguồn, giả định và nhãn loại dữ liệu.', ['Bấm nút của từng báo cáo; báo cáo tác động chọn sự cố rồi xuất .md hoặc In/PDF.'], '<p>Mỗi dòng xuất có cột <code>loai_du_lieu</code> (Pilot / Dự báo / Suy luận) và <code>xuat_luc</code>. Cần quyền Xuất dữ liệu.</p>'),
      S(13, '12 · Đăng nhập, đăng ký, phân quyền (NFR-04)', 'Giới hạn quyền xem/nhập/xuất/cấu hình theo vai trò và ghi nhật ký.', ['Đăng nhập bằng tài khoản dùng thử hoặc tự đăng ký (≥ 8 ký tự, có chữ và số).', 'Bấm tên người dùng góc phải để xem quyền và đăng xuất.'], '<p>Mật khẩu băm SHA-256; sai 5 lần khóa 30 giây; mọi đăng nhập/xuất/bị từ chối ghi vào nhật ký (trang Kiến trúc).</p>', 'Chỉ là bảo mật phía trình duyệt cho prototype; triển khai thật cần máy chủ xác thực + HTTPS.'),
      S(14, '13 · Kiến trúc & Cấu hình (FR-12) và kiểm thử (NFR-08)', 'Xem sơ đồ lớp, chỉnh tham số, chạy bộ ca kiểm thử.', ['Sửa tham số (lịch SX, % FG, ngưỡng, trọng số) → Lưu cấu hình (Admin).', 'Bấm "Chạy kiểm thử" để chạy 9 ca: dữ liệu đủ, thiếu dữ liệu, khóa trùng, quan hệ không tìm thấy, tái lập…'], '<p>Công thức nằm riêng trong <code>js/core/engine.js</code>, tách khỏi giao diện; mỗi quy tắc có mã (R-IMP-01…) và ca kiểm thử.</p>')].join('');
    root.innerHTML = `<div class="callout info">Trang này mô tả đầy đủ cách dùng và thuật toán. Các con số ví dụ được tính trực tiếp từ dữ liệu hiện tại nên khớp với màn hình Impact Analysis.</div>${sec}`;
  } };
})();
