/* Hướng dẫn sử dụng & thuật toán từng chức năng (có ví dụ tính trực tiếp từ dữ liệu) */
(function () {
  FS.pages.guide = { title: 'Hướng dẫn & Thuật toán', sub: 'Mục đích, thao tác và cơ sở thuật toán của từng chức năng', noFilter: true, render(root) {
    const I = FS.tables.incident_truth[0], R = FS.engine.impact(I), C = FS.config, n = FS.fmt.n, top = R.jts[0];
    const S = (id, t, purpose, how, algo, note) => `<details class="fx guide-s" ${id === 1 ? 'open' : ''}><summary>${t}</summary><h4>Dùng để làm gì</h4><p>${purpose}</p><h4>Cách dùng</h4><ol>${how.map(h => `<li>${h}</li>`).join('')}</ol><h4>Thuật toán / công thức</h4>${algo}${note ? `<h4>Lưu ý</h4><p>${note}</p>` : ''}</details>`;
    const sec = [
      S(1, '0 · Tổng quan & bộ lọc toàn cục', 'FlowSight nối các bảng rời rạc (sự cố, sản xuất, Lot, vật tư, JT/Order, giao hàng) thành chuỗi ảnh hưởng có thể kiểm chứng, từ sự cố máy qua tổn thất sản lượng, tồn kho và vật tư, đến đơn hàng và giao hàng.',
        ['Đăng nhập (xem mục 13). Thanh lọc phía trên chọn khoảng ngày, máy/công đoạn, trạng thái sự cố, từ khóa — mọi KPI, biểu đồ, bảng đổi theo.', 'Ô tìm nhanh trên cùng: gõ <code>LOT-0403</code>, <code>INC-0001</code>, <code>JT-0231</code> hoặc mã máy rồi Enter để nhảy tới trang liên quan.', 'Nhãn <i>Đã xác nhận / Suy luận / Chưa đủ dữ liệu / Mô phỏng</i> cho biết độ chắc chắn của từng số liệu.'],
        '<p>Bộ lọc áp dụng lên <code>incident_truth.start_time</code>, <code>station_id</code>, trạng thái (suy ra từ <code>end_time</code> so với thời điểm hệ thống 10/10/2026 12:00, hoặc trạng thái người dùng ghi nhận). Các tổng hợp luôn đếm theo khóa duy nhất (<code>incident_id</code>, <code>jt_id</code>) nên không đếm trùng.</p>', 'Dữ liệu thiếu hiển thị "Chưa đủ dữ liệu", không tự thay bằng 0.'),
      S(2, '1 · Trung tâm Điều hành (FR-01)', 'Cái nhìn nhanh về sự cố và ảnh hưởng sản xuất.', ['Xem 4 thẻ KPI; bấm vào KPI hoặc từng bước của chuỗi tác động để mở danh sách bản ghi tạo nên con số (có tìm kiếm, sắp xếp, xuất CSV).', 'Biểu đồ "Phân bổ nguyên nhân sự cố" có 4 tab: loại nguyên nhân, nhóm lỗi FMEA, máy/công đoạn, mức độ.', 'Khối "Danh mục & vật tư": tiêu thụ vật tư, tồn kho so với tồn an toàn, danh mục sản phẩm, lô vật tư nhận.', 'Khối "Hành động ưu tiên": tích vào hộp khi đã xử lý (cần quyền ghi nhận quyết định).'],
        `<div class="note">Hệ thống liệt kê các sự cố trong khoảng thời gian đã chọn, lọc theo máy và trạng thái.</div>
Sản lượng thực tế = Σ qty_out tại STN-PK ; Kế hoạch = Σ qty_in tại STN-PK
Thiếu ước tính  = Σ_sự cố thiếu hụt ròng (mục 3)
JT có nguy cơ   = |{jt_id : exposure > 0}| (đếm duy nhất giữa các sự cố)
Tiêu thụ vật tư = Σ qty_consumed theo component_id trong kỳ
Tồn so với an toàn: tồn snapshot COMPONENT mới nhất < safety_stock_qty ⇒ cảnh báo
Hành động ưu tiên = top 5 JT theo exposure + tối đa 2 sự cố thiếu liên kết Lot</div>`, 'Sản lượng kế hoạch lấy từ qty_in (lot đã phát hành) vì dữ liệu pilot không có kế hoạch riêng.'),
      S(3, '2 · Incident Monitoring (FR-02)', 'Quản lý sự cố — điểm bắt đầu của phân tích tác động.', ['Bấm một dòng để xem chi tiết: máy, mốc thời gian, FMEA, Lot liên quan, nguồn dữ liệu.', 'Đổi trạng thái (Đang mở / Đang xử lý / Đã đóng) rồi Lưu; lịch sử thay đổi hiển thị bên dưới.', 'Từ chi tiết bấm "Phân tích tác động" hoặc "Lan truyền" để đi tiếp.'],
        '<div class="note">Chi tiết kỹ thuật được mô tả trong tài liệu hệ thống.</div>'),
      S(4, '3 · Impact Analysis (FR-03) — thuật toán chính', 'Ước tính sản lượng mất, thiếu hụt ròng, JT/Order và giao hàng có nguy cơ cho một sự cố, có thể what-if.', ['Chọn sự cố; sửa "Thời gian dừng" (what-if), lịch SX, % FG khả dụng, bật/tắt công suất bù; bấm "Tính lại".', 'Đọc 4 KPI, biểu đồ so sánh, chuỗi ảnh hưởng, bảng JT (bấm dòng để xem căn cứ liên kết).', 'Mở "Giả định & công thức" để tái lập từng bước.'],
        `<div class="note">Hệ thống tính giờ sản xuất bị mất, sản lượng tổn thất và thiếu hụt ròng dựa trên tồn kho hiện có.</div>
<p><b>Ví dụ trực tiếp ${I.incident_id}</b> (${I.station_id}, ${I.duration_h}h): giờ mất ${n(R.lostH)}h × ${n(R.rate)} sp/h = <b>${n(R.lostQty)}</b> sp; FG khả dụng ${n(R.fgUsable)}; thiếu sau tồn ${n(R.deficit)}; bù/ngày ${n(R.perDay)}; thiếu ròng <b>${n(R.net)}</b> sp${top ? `; JT đầu bảng ${top.jt.jt_id} (${top.link}) exposure ${n(top.exposure)}` : ''}.</p>
<p>JT liên quan gồm <b>đã xác nhận</b> (qua khóa <code>jt_allocation_truth</code>: Lot bị ảnh hưởng → JT) và <b>suy luận</b> (quy tắc R-LINK-01: cùng line, hạn giao trong 72h sau sự cố).</p>`, 'Thiếu công suất ⇒ "Chưa đủ dữ liệu"; thiếu JT hoặc tồn kho ⇒ "Ước tính một phần". Không khẳng định giao trễ khi chưa có lịch giao.'),
      S(5, '4 · Propagation (FR-04)', 'Đồ thị lan truyền rủi ro từ sự cố qua máy, lô sản xuất, vật tư, đơn hàng đến giao hàng.', ['Chọn sự cố; bật/tắt từng loại quan hệ (trực tiếp / suy luận / chưa xác minh).', 'Bấm nút hoặc đường nối để xem thuộc tính, nguồn dữ liệu, căn cứ; bảng bên dưới liệt kê mọi liên kết.'],
        '<div class="note">Hệ thống truy vết mối liên hệ giữa sự cố, máy, lô sản xuất, vật tư, đơn hàng và giao hàng.</div>'),
      S(6, '5 · Lot Genealogy (FR-05)', 'Truy ngược nguồn gốc và truy xuôi đối tượng liên quan của một Lot.', ['Nhập Lot ID (gợi ý: LOT-0403, LOT-0404, LOT-2207) → Truy vết.', 'Bấm Lot trong bảng để đi tiếp; xem dòng thời gian công đoạn và kết quả QC; xuất danh sách.'],
        '<div class="note">Truy ngược tìm nguồn gốc lô hàng; truy xuôi xác định phạm vi ảnh hưởng.</div>'),
      S(7, '6 · Root Cause & Evidence (FR-08)', 'Gợi ý yếu tố liên quan và bằng chứng để kỹ sư đánh giá — không tự kết luận nhân quả.', ['Chọn sự cố; đọc bảng yếu tố, bằng chứng, độ tin cậy, trạng thái (Đã xác nhận / Giả thuyết).'],
        '<div class="note">Hệ thống đánh giá các giả thuyết nguyên nhân dựa trên dữ liệu FMEA, lô vật tư dùng chung và kết quả kiểm tra chất lượng.</div>'),
      S(8, '7 · Ưu tiên & Hành động (FR-09)', 'Xếp thứ tự xử lý JT/Order và ghi nhận quyết định.', ['Xem bảng chỉ báo riêng từng JT; bấm dòng để xem lý do và chọn trạng thái (Chưa xem xét / Đang xem xét / Đã chấp nhận / Từ chối / Cần xác minh).', 'Tùy chọn bật "điểm tổng hợp" (trọng số demo, chỉnh ở Kiến trúc & Cấu hình).'],
        `<div class="note">Danh sách được sắp xếp theo mức độ thiếu hụt ước tính và các yếu tố rủi ro khác.</div>`, 'Hệ thống không gửi lệnh điều khiển máy hay đổi kế hoạch.'),
      S('7a', '7a · Phân bổ nguyên nhân sự cố', 'Phân tích chuyên sâu sự cố theo 4 góc nhìn: loại nguyên nhân, nhóm lỗi FMEA, máy/công đoạn, mức độ.',
        ['Bấm tab để đổi cách nhóm (Loại nguyên nhân / Nhóm lỗi FMEA / Máy / Mức độ); biểu đồ donut cập nhật theo.', 'Đọc bảng Top FMEA theo RPN để biết lỗi nào rủi ro nhất (RPN = S×O×D).', 'Bấm một dòng trong bảng chi tiết để nhảy sang Impact Analysis của sự cố đó.'],
        '<div class="note">Thống kê số lượng sự cố và phân loại theo mức độ nghiêm trọng.</div>',
        'Số liệu tuân theo bộ lọc toàn cục (ngày, máy, trạng thái).'),
      S('7b', '7b · Danh mục & vật tư', 'Theo dõi tiêu thụ vật tư, tồn kho so với tồn an toàn, lô vật tư nhận và danh mục sản phẩm.',
        ['Xem biểu đồ donut tiêu thụ vật tư trong kỳ (lọc theo ngày ở thanh trên).', 'Bảng tồn kho: thanh đỏ = dưới tồn an toàn, cần bổ sung; bấm để xem chi tiết.', 'Bảng lô vật tư: bấm một dòng để truy vết genealogy của lô vật tư đó.'],
        '<div class="note">Theo dõi lượng vật tư đã sử dụng và cảnh báo khi tồn kho xuống dưới mức an toàn.</div>',
        'Tồn kho là snapshot tại thời điểm dữ liệu, chưa trừ lượng đã phân bổ cho JT.'),
      S(9, '8 · Data Health (FR-07)', 'Đánh giá chất lượng dữ liệu trước khi phân tích.', ['Xem bảng theo từng bảng dữ liệu; bấm dòng để xem dòng lỗi (dòng, cột, nhóm lỗi); xuất báo cáo.', 'Bật điểm tổng hợp nếu muốn (trọng số demo).'],
        '<div class="note">Đánh giá chất lượng dữ liệu trên các khía cạnh: đầy đủ, hợp lệ, duy nhất, nhất quán và kịp thời.</div>'),
      S(10, '9 · Validation Lab (FR-10)', 'So sánh kết quả engine với ground truth đã xác nhận.', ['Đọc từng ca (F01 tác động, R01 nguyên nhân): tham chiếu vs FlowSight, Khớp/Lệch.', 'Bấm "Lưu phiên bản kiểm chứng" để ghi lại cấu hình và kết quả.'],
        '<div class="note">Chi tiết kỹ thuật được mô tả trong tài liệu hệ thống.</div>', 'Dữ liệu pilot chỉ xác nhận logic hệ thống, không chứng minh độ chính xác thực tế.'),
      S(11, '10 · Import & Data Mapping (FR-06)', 'Nhập CSV riêng theo nhóm, ánh xạ cột, kiểm tra trước khi đưa vào dữ liệu hoạt động.', ['Kéo-thả hoặc chọn CSV (UTF-8); kiểm tra nhóm dữ liệu tự nhận diện, sửa nếu sai.', 'Chỉnh ánh xạ cột nguồn → trường chuẩn; bấm "Kiểm tra dữ liệu"; xem lỗi theo dòng/cột.', '"Xác nhận nhập" chỉ đưa dòng hợp lệ vào bảng (upsert theo khóa); "Xuất CSV đã chuẩn hóa" để tải về. Dùng "Tạo tệp mẫu có lỗi" để thử.'],
        '<div class="note">Chi tiết kỹ thuật được mô tả trong tài liệu hệ thống.</div>', 'Tệp gốc chỉ được đọc, không bị sửa. Cần quyền Nhập dữ liệu.'),
      S(12, '11 · Báo cáo & Xuất (FR-11)', 'Xuất CSV/Markdown có thời điểm, nguồn, giả định và nhãn loại dữ liệu.', ['Bấm nút của từng báo cáo; báo cáo tác động chọn sự cố rồi xuất .md hoặc In/PDF.'], '<p>Mỗi dòng xuất có cột <code>loai_du_lieu</code> (Pilot / Dự báo / Suy luận) và <code>xuat_luc</code>. Cần quyền Xuất dữ liệu.</p>'),
      S(13, '12 · Đăng nhập, đăng ký, phân quyền (NFR-04)', 'Giới hạn quyền xem/nhập/xuất/cấu hình theo vai trò và ghi nhật ký.', ['Đăng nhập bằng tài khoản dùng thử hoặc tự đăng ký (≥ 8 ký tự, có chữ và số).', 'Bấm tên người dùng góc phải để xem quyền và đăng xuất.'], '<p>Mật khẩu băm SHA-256; sai 5 lần khóa 30 giây; mọi đăng nhập/xuất/bị từ chối ghi vào nhật ký (trang Kiến trúc).</p>', 'Chỉ là bảo mật phía trình duyệt cho prototype; triển khai thật cần máy chủ xác thực + HTTPS.'),
      S(14, '13 · Kiến trúc & Cấu hình (FR-12) và kiểm thử (NFR-08)', 'Xem sơ đồ lớp, chỉnh tham số, chạy bộ ca kiểm thử.', ['Sửa tham số (lịch SX, % FG, ngưỡng, trọng số) → Lưu cấu hình (Admin).', 'Bấm "Chạy kiểm thử" để chạy 9 ca: dữ liệu đủ, thiếu dữ liệu, khóa trùng, quan hệ không tìm thấy, tái lập…'], '<p>Công thức nằm riêng trong <code>js/core/engine.js</code>, tách khỏi giao diện; mỗi quy tắc có mã (R-IMP-01…) và ca kiểm thử.</p>')].join('');
    root.innerHTML = `<div class="callout info">Trang này mô tả đầy đủ cách dùng và thuật toán. Các con số ví dụ được tính trực tiếp từ dữ liệu hiện tại nên khớp với màn hình Impact Analysis.</div>${sec}`;
  } };
})();
