/* FR-07 Data Quality & Health */
(function () {
  const u = FS.ui, DIMS = ['Completeness', 'Validity', 'Uniqueness', 'Consistency', 'Referential Integrity'];
  FS.qw = FS.persist.get('qw', { Completeness: 25, Validity: 20, Uniqueness: 20, Consistency: 15, 'Referential Integrity': 20, on: false });
  const pc = v => v == null ? '<span class="muted">N/A</span>' : `<b style="color:${v >= .99 ? '#127a47' : v >= .9 ? '#9a5b00' : '#c52a2a'}">${(v * 100).toFixed(1)}%</b>`;
  FS.pages.health = { title: 'Data Health', sub: 'Đánh giá độ phù hợp của dữ liệu trước khi dùng cho phân tích', noFilter: true, render(root) {
    const Q = Object.keys(FS.SCHEMA).filter(g => FS.tables[g]).map(g => FS.quality(g, FS.tables[g])), W = FS.qw, tw = DIMS.reduce((s, d) => s + W[d], 0);
    const score = q => { let s = 0, w = 0; DIMS.forEach(d => { if (q.dims[d] != null) { s += q.dims[d] * W[d]; w += W[d]; } }); return w ? s / w : null; };
    const tot = Q.reduce((s, q) => s + q.rows, 0), bad = Q.reduce((s, q) => s + q.bad, 0), iss = Q.flatMap(q => q.issues.map(i => ({ ...i, table: q.group })));
    const common = Object.entries(iss.reduce((m, i) => (m[i.type] = (m[i.type] || 0) + 1, m), {})).map(([k, v]) => ({ k, v, c: u.C.amber }));
    const fk = Q.reduce((a, q) => ({ ok: a.ok + q.fk.ok, tot: a.tot + q.fk.tot }), { ok: 0, tot: 0 });
    root.innerHTML = `<div class="grid g4">${u.kpi({ label: 'Tổng dòng kiểm tra', value: tot, icon: '☰', color: 'blue', sub: Q.length + ' bảng' })}${u.kpi({ label: 'Dòng đạt', value: tot - bad, icon: '✔', color: 'green' })}${u.kpi({ label: 'Dòng có cảnh báo/lỗi', value: bad, icon: '⚠', color: 'red' })}${u.kpi({ label: 'Tỷ lệ liên kết khóa', value: fk.tot ? fk.ok / fk.tot * 100 : 0, unit: '%', icon: '⇄', color: 'violet', nodata: !fk.tot, sub: `${fk.ok}/${fk.tot} khóa tìm thấy`, def: 'Referential Integrity toàn bộ khóa ngoại' })}</div>
    <div class="grid g21 mt"><div class="card"><div class="card-h"><h3>Chất lượng theo bảng</h3><small>Bấm dòng để xem dòng dữ liệu lỗi</small><span class="sp"><button class="btn sm ghost" id="ex">⭳ Xuất báo cáo kiểm tra</button></span></div><div id="t"></div></div>
      <div class="card"><div class="card-h"><h3>Nhóm lỗi phổ biến</h3></div>${common.length ? u.bars(common) : u.empty('Không có lỗi')}<div class="callout info" style="font-size:12px">Lot ID lặp lại trong bảng sự kiện là hợp lệ: khóa được đánh giá theo đúng cấp dữ liệu.</div></div></div>
    <div class="card mt"><div class="card-h"><h3>Điểm chất lượng tổng hợp</h3><span class="sp"><label class="row"><input type="checkbox" id="qon" ${W.on ? 'checked' : ''}> Tính điểm theo trọng số</label></span></div>
      ${W.on ? `<div class="callout warn">Trọng số demo, chưa được xác nhận. Timeliness không đưa vào điểm vì chưa có ngưỡng.</div><div class="cfg">${DIMS.map(d => `<label>${d} (%)<input type="number" data-w="${d}" value="${W[d]}" min="0" max="100"></label>`).join('')}</div><p>Điểm toàn hệ thống: <span class="score">${(Q.reduce((s, q) => s + (score(q) || 0), 0) / Q.length * 100).toFixed(1)}</span> / 100</p>` : '<small class="muted">Chưa bật: chỉ hiển thị từng chiều riêng lẻ, không tạo điểm tổng khi công thức & trọng số chưa xác định.</small>'}</div>`;
    u.$('#qon', root).onchange = e => { W.on = e.target.checked; FS.persist.set('qw', W); FS.go(); }; u.$$('[data-w]', root).forEach(i => i.onchange = () => { W[i.dataset.w] = +i.value; FS.persist.set('qw', W); FS.go(); });
    u.table(u.$('#t', root), { rows: Q, export: 'chat_luong_du_lieu', pageSize: 12, search: false, onRow: q => FS.drill('Dòng lỗi · ' + q.label, [{ k: 'row', t: 'Dòng' }, { k: 'col', t: 'Cột' }, { t: 'Nhóm', r: i => u.badge(i.type, 'amber'), x: i => i.type }, { k: 'msg', t: 'Mô tả' }], q.issues, 'loi_' + q.group),
      cols: [{ t: 'Bảng', r: q => `<b>${q.label}</b><br><small>${q.group}${FS.TABLE_ORIGIN[q.group] === 'Pilot' ? '' : ' · đã nhập'}</small>`, x: q => q.label }, { k: 'rows', t: 'Dòng' }, { k: 'good', t: 'Đạt' }, { k: 'bad', t: 'Lỗi' }, ...DIMS.map(d => ({ t: d.replace('Referential Integrity', 'Ref. Integrity'), r: q => pc(q.dims[d]), x: q => q.dims[d] == null ? '' : (q.dims[d] * 100).toFixed(1), s: q => q.dims[d] ?? 2 })), { t: 'Độ mới', r: q => q.dims.Timeliness == null ? 'N/A' : q.dims.Timeliness.toFixed(1) + ' ngày', x: q => q.dims.Timeliness }, ...(W.on ? [{ t: 'Điểm', r: q => (score(q) * 100).toFixed(1), x: q => score(q) }] : [])] });
    u.$('#ex', root).onclick = () => { FS.csv.download('bao_cao_chat_luong_du_lieu.csv', FS.csv.stringify(iss.map(i => ({ bang: i.table, dong: i.row, cot: i.col, nhom: i.type, mo_ta: i.msg, nguon: FS.TABLE_ORIGIN[i.table] })))); u.toast('Đã xuất báo cáo kiểm tra'); };
  } };
})();
