/* FR-06 Data Import & Mapping: tải CSV → xác định nhóm → ánh xạ → kiểm tra → xác nhận. Tệp gốc không bị sửa. */
(function () {
  const u = FS.ui; let S = { state: 'Chưa tải lên', file: null, parsed: null, group: null, map: {}, result: null, progress: 0 };
  const STATES = ['Chưa tải lên', 'Đang kiểm tra', 'Hợp lệ', 'Hợp lệ một phần', 'Không hợp lệ', 'Đã nhập'], SC = { 'Chưa tải lên': 'gray', 'Đang kiểm tra': 'blue', 'Hợp lệ': 'green', 'Hợp lệ một phần': 'amber', 'Không hợp lệ': 'red', 'Đã nhập': 'green' };
  const fields = g => { const s = FS.SCHEMA[g]; return [...new Set([...s.req, ...s.key, ...s.dates, ...s.nums, ...Object.keys(s.enums || {}), ...(s.fk || []).map(f => f.f)])]; };
  function normalize() { const P = S.parsed, F = fields(S.group); return P.rows.map(r => { const o = {}; F.forEach(f => { const c = S.map[f], i = c ? P.headers.indexOf(c) : -1; o[f] = i >= 0 ? FS.csv.coerce(f, r[i]) : null; }); return o; }); }
  async function validate(root) {
    S.state = 'Đang kiểm tra'; S.progress = 0; paint(root); const rows = normalize(), miss = FS.SCHEMA[S.group].req.filter(f => !S.map[f]);
    for (let i = 0; i < rows.length; i += 1500) { S.progress = Math.round(i / rows.length * 100); const b = u.$('#pb', root); if (b) b.style.width = S.progress + '%'; await new Promise(r => setTimeout(r, 0)); }
    const refs = t => (t === S.group ? rows : FS.tables[t] || []), q = FS.quality(S.group, rows, refs); q.issues = q.issues.concat(miss.map(f => ({ row: '—', col: f, type: 'Completeness', msg: 'Trường bắt buộc chưa được ánh xạ' })));
    const badRows = new Set(q.issues.filter(i => i.row !== '—').map(i => i.row - 2)); S.result = { rows, q, badRows, valid: rows.filter((_, i) => !badRows.has(i)), miss };
    S.state = miss.length || !S.result.valid.length ? 'Không hợp lệ' : badRows.size ? 'Hợp lệ một phần' : 'Hợp lệ'; paint(root);
  }
  function load(name, text, root) { const P = FS.csv.parse(text); S = { state: 'Chưa tải lên', file: name, size: text.length, parsed: P, group: FS.detectGroup(P.headers), map: {}, result: null, progress: 0, at: new Date().toISOString().slice(0, 19) }; if (S.group) S.map = FS.autoMap(P.headers, S.group); paint(root); }
  function paint(root) {
    const P = S.parsed, R = S.result, step = !P ? 0 : !R ? 2 : S.state === 'Đã nhập' ? 5 : 4;
    root.innerHTML = `<div class="steps">${['Chọn tệp', 'Xác định nhóm', 'Ánh xạ cột', 'Kiểm tra', 'Xác nhận', 'Đã nhập'].map((s, i) => `<span class="${i < step ? 'done' : i === step ? 'on' : ''}">${i + 1}. ${s}</span>`).join('')}<span class="sp">${u.badge(S.state, SC[S.state])}</span></div>
    <div class="grid g21"><div class="card"><div class="drop" id="dz"><div style="font-size:34px">⇪</div><b>Kéo-thả CSV vào đây hoặc bấm để chọn</b><p class="muted">UTF-8 · tệp gốc chỉ được đọc, không bị sửa đổi · dữ liệu xử lý ngay trong trình duyệt</p><input type="file" id="fi" accept=".csv,text/csv" hidden multiple></div>
      <div class="row mt"><button class="btn ghost sm" id="smp">Tạo tệp mẫu có lỗi</button><button class="btn ghost sm" id="rst">↺ Khôi phục dữ liệu gốc</button></div></div>
      <div class="card"><h3>Nhật ký nhập</h3>${FS.wf.imports.slice(0, 6).map(l => `<div class="tl"><div><b>${u.esc(l.file)}</b> → ${l.group}<br><small>${l.t} · ${l.valid} hợp lệ / ${l.err} lỗi</small></div></div>`).join('') || '<small class="muted">Chưa có lần nhập nào.</small>'}</div></div>
    ${P ? `<div class="card mt"><div class="card-h"><h3>${u.esc(S.file)}</h3><small>${P.rows.length} dòng · ${P.headers.length} cột</small><span class="sp"><label class="row">Nhóm dữ liệu <select id="gp"><option value="">— chọn —</option>${Object.entries(FS.SCHEMA).map(([k, v]) => `<option value="${k}" ${k === S.group ? 'selected' : ''}>${v.label} (${k})</option>`).join('')}</select></label></span></div>
      ${S.group ? '' : '<div class="callout warn">Không tự nhận diện được nhóm dữ liệu — chọn thủ công.</div>'}<div id="pv"></div></div>` : ''}
    ${P && S.group ? `<div class="card mt"><div class="card-h"><h3>Ánh xạ cột nguồn → trường chuẩn</h3><span class="sp"><button class="btn" id="vd">Kiểm tra dữ liệu</button></span></div>${fields(S.group).map(f => { const req = FS.SCHEMA[S.group].req.includes(f), ok = !!S.map[f]; return `<div class="map-row ${req && !ok ? 'miss' : ''}"><select data-f="${f}"><option value="">— bỏ qua —</option>${P.headers.map(h => `<option ${S.map[f] === h ? 'selected' : ''}>${u.esc(h)}</option>`).join('')}</select><span>→</span><b>${f}${req ? ' <span style="color:#ef4444">*</span>' : ''}</b>${ok ? u.badge(S.map[f] === f ? 'Khớp' : 'Đã ánh xạ', 'green', '✔') : req ? u.badge('Thiếu', 'red', '✕') : u.badge('Tùy chọn', 'gray')}</div>`; }).join('')}</div>` : ''}
    ${S.state === 'Đang kiểm tra' ? `<div class="card mt"><b>Đang kiểm tra…</b><div class="bar mt"><i id="pb" style="width:${S.progress}%"></i></div></div>` : ''}
    ${R ? `<div class="grid g4 mt">${u.kpi({ label: 'Dòng hợp lệ', value: R.valid.length, icon: '✔', color: 'green' })}${u.kpi({ label: 'Dòng lỗi', value: R.badRows.size, icon: '✕', color: 'red' })}${u.kpi({ label: 'Số lỗi/cảnh báo', value: R.q.issues.length, icon: '⚠', color: 'amber' })}${u.kpi({ label: 'Trạng thái', value: 0, icon: '◎', color: 'blue', nodata: true, sub: S.state })}</div>
      <div class="card mt"><div class="card-h"><h3>Lỗi theo dòng & cột</h3><small>Xem lỗi trước khi xác nhận</small></div><div id="er"></div>
        <div class="row mt">${S.state !== 'Không hợp lệ' && S.state !== 'Đã nhập' ? `<button class="btn" id="ok">Xác nhận nhập ${R.valid.length} dòng hợp lệ</button>` : ''}<button class="btn ghost" id="nx">⭳ Xuất CSV đã chuẩn hóa</button>${S.state === 'Không hợp lệ' ? '<span class="callout err" style="margin:0">Sửa ánh xạ hoặc tải lại tệp để tiếp tục.</span>' : ''}</div></div>` : ''}`;
    const dz = u.$('#dz', root), fi = u.$('#fi', root); dz.onclick = () => fi.click();
    const rd = f => { const r = new FileReader(); r.onload = () => load(f.name, r.result, root); r.onerror = () => u.toast('Không đọc được tệp', 'err'); r.readAsText(f, 'utf-8'); };
    fi.onchange = () => fi.files[0] && rd(fi.files[0]); ['dragover', 'dragenter'].forEach(e => dz.addEventListener(e, ev => { ev.preventDefault(); dz.classList.add('over'); })); ['dragleave', 'drop'].forEach(e => dz.addEventListener(e, ev => { ev.preventDefault(); dz.classList.remove('over'); })); dz.addEventListener('drop', ev => ev.dataTransfer.files[0] && rd(ev.dataTransfer.files[0]));
    u.$('#smp', root).onclick = () => { const rows = FS.tables.incident_truth.slice(0, 20).map((r, i) => ({ 'Mã sự cố': i === 5 ? r.incident_id.replace(/\d$/, '1') : r.incident_id, 'Máy': r.station_id, 'Bắt đầu': i === 3 ? '31/13/2026' : r.start_time, 'Kết thúc': r.end_time, duration_h: i === 7 ? 'abc' : r.duration_h, affected_lots: i === 9 ? 'LOT-9999' : r.affected_lots, fmea_code: r.fmea_code })); rows[11]['Mã sự cố'] = ''; load('mau_su_co_co_loi.csv', FS.csv.stringify(rows), root); };
    u.$('#rst', root).onclick = () => { FS.loadBundle(); S = { state: 'Chưa tải lên', result: null, parsed: null, progress: 0 }; u.toast('Đã khôi phục dữ liệu gốc'); paint(root); };
    if (!P) return; u.table(u.$('#pv', root), { rows: FS.csv.toObjects({ headers: P.headers, rows: P.rows.slice(0, 50) }, false), cols: P.headers.map(h => ({ k: h, t: u.esc(h) })), pageSize: 5, search: false });
    const gp = u.$('#gp', root); gp.onchange = () => { S.group = gp.value || null; S.result = null; S.map = S.group ? FS.autoMap(P.headers, S.group) : {}; paint(root); };
    u.$$('[data-f]', root).forEach(s => s.onchange = () => { S.map[s.dataset.f] = s.value || undefined; S.result = null; S.state = 'Chưa tải lên'; paint(root); }); const vd = u.$('#vd', root); if (vd) vd.onclick = () => validate(root);
    if (R) { u.table(u.$('#er', root), { rows: R.q.issues, pageSize: 8, export: 'loi_nhap_' + S.group, empty: 'Không có lỗi', cols: [{ k: 'row', t: 'Dòng' }, { k: 'col', t: 'Cột' }, { t: 'Nhóm', r: i => u.badge(i.type, 'amber'), x: i => i.type }, { k: 'msg', t: 'Mô tả' }] });
      u.$('#nx', root).onclick = () => FS.csv.download('chuan_hoa_' + S.group + '.csv', FS.csv.stringify(R.valid));
      const ok = u.$('#ok', root); if (ok) ok.onclick = () => { const key = FS.SCHEMA[S.group].key, T = FS.tables[S.group] || (FS.tables[S.group] = []), kf = r => key.map(k => r[k]).join('|'), ex = new Map(T.map((r, i) => [kf(r), i]));
        R.valid.forEach(r => { const i = ex.get(kf(r)); i != null ? T[i] = { ...T[i], ...r } : T.push(r); }); FS.TABLE_ORIGIN[S.group] = 'Đã nhập (người dùng)'; FS.reindex(); FS.wf.imports.unshift({ file: S.file, group: S.group, t: S.at, valid: R.valid.length, err: R.badRows.size }); FS.saveWf(); S.state = 'Đã nhập'; u.toast(`Đã nhập ${R.valid.length} dòng vào ${S.group}`); paint(root); }; }
  }
  FS.pages.import = { title: 'Nhập liệu & Ánh xạ', sub: 'Tải lên CSV, ánh xạ trường dữ liệu và kiểm tra tính hợp lệ trước khi nhập', noFilter: true, render(root) { if (!FS.auth.can('import')) { root.innerHTML = '<div class="card">' + u.empty('Không có quyền nhập dữ liệu', 'Vai trò hiện tại chỉ được xem. Đăng nhập bằng tài khoản Admin hoặc Analyst / Data Engineer.') + '</div>'; return; } S = { state: 'Chưa tải lên', result: null, parsed: null, progress: 0 }; paint(root); } };
})();
