/* FR-09 Ưu tiên & đề xuất hành động */
(function () {
  const u = FS.ui, STS = ['Chưa xem xét', 'Đang xem xét', 'Đã chấp nhận', 'Từ chối', 'Cần xác minh'];
  FS.pages.priority = { title: 'Ưu tiên & Hành động', sub: 'Xếp hạng theo từng chỉ báo; điểm tổng hợp chỉ khi trọng số được xác nhận', render(root) {
    const R = FS.engine.impactAll(), C = FS.config, map = new Map();
    R.forEach(r => r.jts.forEach(x => { const o = map.get(x.jt.jt_id); if (!o || x.exposure > o.x.exposure) map.set(x.jt.jt_id, { x, r, breadth: r.jts.length }); }));
    const rows = [...map.values()].filter(o => o.x.exposure > 0).map(o => { const x = o.x, rec = o.r.perDay ? (o.r.deficit / o.r.perDay) * 24 : null, conf = o.r.status === 'Đủ dữ liệu' ? 1 : o.r.status === 'Ước tính một phần' ? .6 : .3;
      const n = { s: Math.min(1, x.ratio), sl: x.slackH <= 0 ? 1 : Math.max(0, 1 - x.slackH / 96), l: x.link === 'Đã xác nhận' ? 1 : .5, b: Math.min(1, o.breadth / 10), c: conf };
      const W = C.wShort + C.wSlack + C.wLink + C.wBreadth + C.wConf, score = (n.s * C.wShort + n.sl * C.wSlack + n.l * C.wLink + n.b * C.wBreadth + n.c * C.wConf) / W * 100;
      return { id: x.jt.jt_id, jt: x.jt, inc: o.r.inc.incident_id, short: x.exposure, ratio: x.ratio, slack: x.slackH, fg: o.r.fgUsable, rec, breadth: o.breadth, conf, link: x.link, risk: x.risk, score, why: `Thiếu ${FS.fmt.n(x.exposure)} sp (${Math.round(x.ratio * 100)}% đơn), slack ${FS.fmt.n(x.slackH)}h, ${x.link.toLowerCase()}, FG khả dụng ${FS.fmt.n(o.r.fgUsable)}` }; });
    rows.sort((a, b) => C.useWeights ? b.score - a.score : b.short - a.short);
    root.innerHTML = `<div class="card"><div class="card-h"><h3>Cách xếp hạng</h3><span class="sp"><label class="row"><input type="checkbox" id="uw" ${C.useWeights ? 'checked' : ''}> Dùng điểm tổng hợp (trọng số demo)</label></span></div>
      ${C.useWeights ? `<div class="callout warn">Trọng số đang dùng là <b>demo, chưa được DENSO xác nhận</b>: thiếu hụt ${C.wShort} · slack ${C.wSlack} · liên kết ${C.wLink} · lan truyền ${C.wBreadth} · tin cậy ${C.wConf}. Chỉnh tại Kiến trúc & Cấu hình.</div>` : '<div class="callout info">Chưa có trọng số thống nhất → hiển thị <b>từng chỉ báo riêng</b>, sắp xếp theo thiếu hụt ước tính. Không tạo điểm ưu tiên tổng hợp.</div>'}</div>
    <div class="card mt"><div class="card-h"><h3>Thứ tự xử lý JT/Order</h3><small>Bấm dòng để xem lý do & ghi nhận quyết định</small></div><div id="t"></div></div>
    <div class="card mt"><div class="card-h"><h3>Lịch sử quyết định</h3></div>${FS.wf.hist.filter(h => h.what.startsWith('JT')).slice(0, 8).map(h => `<div class="tl"><div><b>${h.what}</b> <small>${h.t}</small></div></div>`).join('') || '<small class="muted">Chưa có quyết định nào.</small>'}</div>
    <div class="callout info">FlowSight không gửi lệnh điều khiển máy hay đổi kế hoạch trong hệ thống nguồn; mọi đề xuất chỉ để người dùng xem xét.</div>`;
    u.$('#uw', root).onchange = e => { C.useWeights = e.target.checked; FS.saveConfig('Bật/tắt điểm tổng hợp'); FS.go(); };
    u.table(u.$('#t', root), { rows, export: 'uu_tien_jt', pageSize: 10, empty: 'Chưa có JT có nguy cơ trong phạm vi lọc', onRow: r => detail(r), cols: [{ t: '#', r: r => rows.indexOf(r) + 1, x: r => rows.indexOf(r) + 1 }, { k: 'id', t: 'JT/Order' }, { k: 'inc', t: 'Sự cố' }, { t: 'Thiếu (sp)', r: r => FS.fmt.n(r.short), x: r => r.short, s: r => r.short }, { t: 'Slack (h)', r: r => FS.fmt.n(r.slack), x: r => r.slack, s: r => r.slack }, { t: 'FG khả dụng', r: r => FS.fmt.n(r.fg), x: r => r.fg }, { t: 'Phục hồi (h)', r: r => r.rec == null ? '—' : FS.fmt.n(r.rec), x: r => r.rec }, { t: 'Phạm vi', r: r => r.breadth + ' JT', x: r => r.breadth }, { t: 'Tin cậy DL', r: r => Math.round(r.conf * 100) + '%', x: r => r.conf }, ...(C.useWeights ? [{ t: 'Điểm', r: r => `<b>${FS.fmt.n(r.score)}</b>`, x: r => r.score, s: r => r.score }] : []), { t: 'Rủi ro', r: r => u.badge(r.risk.t, r.risk.c, r.risk.i), x: r => r.risk.t }, { t: 'Quyết định', r: r => u.badge(FS.wf.act[r.id] || 'Chưa xem xét', FS.wf.act[r.id] === 'Đã chấp nhận' ? 'green' : FS.wf.act[r.id] === 'Từ chối' ? 'red' : 'gray'), x: r => FS.wf.act[r.id] || 'Chưa xem xét' }] });
    function detail(r) {
      const m = u.modal('Đề xuất cho ' + r.id, `${u.kv([['Vì sao xếp ưu tiên', r.why], ['Điều kiện áp dụng', 'Dữ liệu ' + (r.conf === 1 ? 'đủ' : 'chưa đầy đủ') + '; giả định tồn FG khả dụng ' + C.fgUsablePct + '%'], ['Đề xuất', 'Xem xét tái sắp xếp lịch & tăng ca bù tại ' + (FS.tables.incident_truth.find(i => i.incident_id === r.inc) || {}).station_id + '; xác nhận tồn FG và lịch giao với Delivery.'], ['Dữ liệu hỗ trợ', `Sự cố ${r.inc} · jt_order_truth · inventory_truth`]])}
        <div class="row mt"><select id="st">${STS.map(s => `<option ${s === (FS.wf.act[r.id] || 'Chưa xem xét') ? 'selected' : ''}>${s}</option>`).join('')}</select><button class="btn" id="sv">Ghi nhận</button></div>`);
      u.$('#sv', m.el).onclick = () => { if (!FS.auth.need('decide')) return; FS.wf.act[r.id] = u.$('#st', m.el).value; FS.wf.hist.unshift({ t: new Date().toISOString().slice(0, 19), what: 'JT ' + r.id + ' → ' + FS.wf.act[r.id] }); FS.saveWf(); m.close(); u.toast('Đã ghi nhận quyết định'); FS.go(); };
    }
  } };
})();
