/* FR-11 Reports & Export — mọi báo cáo phân biệt Thực tế / Pilot / Suy luận */
(function () {
  const u = FS.ui, PV = r => r === 'Suy luận' ? 'Suy luận' : 'Pilot';
  FS.pages.reports = { title: 'Báo cáo & Xuất dữ liệu', sub: 'Mỗi báo cáo kèm thời điểm, nguồn, giả định và loại dữ liệu', render(root) {
    const stamp = new Date().toISOString().slice(0, 19), R = FS.engine.impactAll(), incs = FS.engine.incidents();
    const items = [
      ['Danh sách sự cố & đối tượng liên quan', 'Sự cố, máy, FMEA, Lot, JT liên quan', () => FS.csv.stringify(R.flatMap(r => (r.jts.length ? r.jts : [null]).map(x => ({ incident_id: r.inc.incident_id, station_id: r.inc.station_id, bat_dau: r.inc.start_time, gio_dung: r.inc.duration_h, fmea: r.inc.fmea_code, lot_lien_quan: r.inc.affected_lots, jt_lien_quan: x ? x.jt.jt_id : '', muc_lien_ket: x ? x.link : 'Chưa đủ dữ liệu liên kết', loai_du_lieu: x ? PV(x.link) : 'Pilot', xuat_luc: stamp })))), 'su_co_doi_tuong'],
      ['Bảng JT/Order có nguy cơ', 'Thiếu hụt ước tính, slack, liên kết', () => FS.csv.stringify(R.flatMap(r => r.atRisk.map(x => ({ jt_id: x.jt.jt_id, san_pham: x.jt.product_id, so_luong: x.jt.qty, han_giao: x.jt.due_ts, thieu_uoc_tinh: Math.round(x.exposure), slack_h: Math.round(x.slackH * 10) / 10, rui_ro: x.risk.t, lien_ket: x.link, su_co: r.inc.incident_id, loai_du_lieu: 'Dự báo/' + PV(x.link), gia_dinh: `ca ${FS.config.schedStart}-${FS.config.schedEnd}h; FG khả dụng ${FS.config.fgUsablePct}%`, xuat_luc: stamp })))), 'jt_nguy_co'],
      ['Kết quả kiểm tra chất lượng dữ liệu', 'Dòng lỗi theo bảng/cột', () => FS.csv.stringify(Object.keys(FS.SCHEMA).filter(g => FS.tables[g]).flatMap(g => FS.quality(g, FS.tables[g]).issues.map(i => ({ bang: g, dong: i.row, cot: i.col, nhom: i.type, mo_ta: i.msg, loai_du_lieu: FS.TABLE_ORIGIN[g], xuat_luc: stamp })))), 'chat_luong_du_lieu'],
      ['Bảng dữ liệu đã chuẩn hóa', 'Tập Lot + sự kiện sản xuất đang hoạt động', () => FS.csv.stringify(FS.tables.canonical_lots.map(l => ({ ...l, loai_du_lieu: FS.TABLE_ORIGIN.canonical_lots }))), 'canonical_lots_chuan_hoa']];
    root.innerHTML = `<div class="grid g2">${items.map((it, i) => `<div class="card"><h3>${it[0]}</h3><p class="muted">${it[1]}</p><button class="btn" data-i="${i}">⭳ Xuất CSV</button></div>`).join('')}</div>
    <div class="card mt"><div class="card-h"><h3>Báo cáo tác động (Markdown)</h3></div><div class="row"><label>Sự cố<select id="i">${incs.map(i => `<option>${i.incident_id}</option>`).join('')}</select></label><button class="btn" id="md">⭳ Xuất báo cáo</button><button class="btn ghost" onclick="window.print()"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect width="12" height="8" x="6" y="14"/></svg> In / PDF</button></div><small class="muted">Kèm thời điểm, nguồn, đầu vào, công thức, giả định và nhãn Thực tế/Pilot/Suy luận.</small></div>`;
    u.$$('[data-i]', root).forEach(b => b.onclick = () => { const it = items[+b.dataset.i]; FS.csv.download(it[3] + '.csv', it[2]()); u.toast('Đã xuất ' + it[3] + '.csv'); });
    u.$('#md', root).onclick = () => { const inc = incs.find(i => i.incident_id === u.$('#i', root).value) || incs[0]; if (!inc) return u.toast('Không có sự cố', 'warn'); const r = FS.engine.impact(inc);
      const md = `# Báo cáo tác động ${inc.incident_id}\n\n- Xuất lúc: ${stamp}\n- Loại dữ liệu: **Mô phỏng** (nguồn: flowsight-data ground truth)\n- Tình trạng dữ liệu: ${r.status}\n\n## Đầu vào\n- Máy: ${inc.station_id} · Dừng ${inc.start_time} → ${inc.end_time} (${inc.duration_h}h) · FMEA ${inc.fmea_code}\n- Lot liên quan: ${inc.affected_lots || 'Chưa đủ dữ liệu liên kết'}\n\n## Tính toán (dự báo)\n| Bước | Giá trị | Công thức |\n|---|---|---|\n${r.steps.map(s => `| ${s[0]} | ${s[1]} | ${s[2]} |`).join('\n')}\n\n## JT/Order liên quan\n| JT | SL | Hạn giao | Thiếu ước tính | Liên kết | Rủi ro |\n|---|---|---|---|---|---|\n${r.jts.map(x => `| ${x.jt.jt_id} | ${x.jt.qty} | ${x.jt.due_ts} | ${FS.fmt.n(x.exposure)} | ${x.link} | ${x.risk.t} |`).join('\n') || '| — | | | | Chưa đủ dữ liệu liên kết | |'}\n\n## Giả định\n${r.assume.map(a => '- ' + a).join('\n')}\n- Ngưỡng rủi ro: ${FS.config.thresholdOn ? `Cao ≥ ${FS.config.thHigh}%, TB ≥ ${FS.config.thMid}% (ngưỡng dung sai quy định)` : 'Chưa cấu hình ngưỡng'}\n- Cấu hình: ${FS.config.version}\n\n> Kết quả hỗ trợ quyết định, không thay thế đánh giá của kỹ sư và không tự thay đổi kế hoạch sản xuất.\n`;
      FS.csv.download('bao_cao_tac_dong_' + inc.incident_id + '.md', md, 'text/markdown;charset=utf-8'); u.toast('Đã xuất báo cáo'); };
  } };
})();
