/* FR-10 Validation Lab: so sánh kết quả engine với ground truth */
(function () {
  const u = FS.ui, jset = a => [...new Set(a)].sort();
  function f01() { const t = FS.json.impact_truth_F01.expected_result, inc = FS.tables.incident_truth.find(i => i.test_case_link === 'F01'), R = FS.engine.impact(inc), late = jset(R.atRisk.map(x => x.jt.jt_id)), exp = jset(t.jt_late), tp = late.filter(x => exp.includes(x)).length;
    return { id: 'F01', name: 'Tác động sự cố ' + inc.incident_id, rows: [['Thiếu hụt ròng (sp)', t.shortfall_qty, R.net == null ? null : Math.round(R.net)], ['JT trễ', exp.join(', '), late.join(', ') || '(không có)'], ['Lot bị ảnh hưởng', jset(t.affected_lots).join(', '), jset(R.lots).join(', ')], ['FMEA', t.fmea_code, inc.fmea_code], ['RPN', t.rpn, inc.rpn]],
      m: { err: R.net == null ? null : R.net - t.shortfall_qty, ape: R.net == null ? null : Math.abs(R.net - t.shortfall_qty) / t.shortfall_qty, p: late.length ? tp / late.length : 0, r: exp.length ? tp / exp.length : 0 }, note: 'P_late tham chiếu = ' + t.P_late + ' (engine hiện chưa ước tính xác suất — không so sánh).' }; }
  function r01() { const t = FS.json.cause_truth_R01.expected_result, inc = FS.tables.incident_truth.find(i => i.test_case_link === 'R01'), F = FS.engine.cause(inc).filter(f => f.kind === 'Vật tư').sort((a, b) => b.conf - a.conf), top = F[0] ? F[0].factor.replace('Lô vật tư chung: ', '') : null;
    return { id: 'R01', name: 'Nguyên nhân sự cố ' + inc.incident_id, rows: [['Nguyên nhân hàng đầu', t.top_cause, top || '(chưa đủ bằng chứng)'], ['Loại nguyên nhân', t.cause_type, inc.root_cause_type], ['FMEA', t.fmea_code, inc.fmea_code], ['Lot cần cô lập', jset(t.isolate_lots).join(', '), jset(FS.lotList(inc.affected_lots)).join(', ')], ['Độ tin cậy', t.confidence, F[0] ? F[0].conf : null]], m: { hit: top === t.top_cause ? 1 : 0 }, note: 'Độ tin cậy của engine là heuristic (tỷ lệ Lot chung lô vật tư), không phải xác suất hiệu chỉnh.' }; }
  FS.pages.validation = { title: 'Kiểm chứng Mô hình', sub: 'Đối chiếu kết quả phân tích với dữ liệu tham chiếu đã xác nhận', noFilter: true, render(root) {
    const cases = [f01(), r01()], dh = Object.fromEntries(Object.entries(FS.json || {}).filter(([k]) => k.startsWith('data_health_truth_'))), runs = FS.persist.get('valruns', []);
    root.innerHTML = `<div class="callout warn"><b>Phạm vi kiểm chứng:</b> dữ liệu tham chiếu là <b>mô phỏng</b> (${Object.keys(FS.json).length} tệp ground truth). Kết quả chỉ xác nhận <b>logic hệ thống</b>, không chứng minh hiệu năng thực tế tại nhà máy. Chỉ có 2 ca có tham chiếu (F01, R01) nên <b>không công bố độ chính xác tổng thể</b>.</div>
    ${cases.map(c => { const ok = (a, b) => String(a) === String(b); return `<div class="card mt"><div class="card-h"><h3>${c.id} · ${c.name}</h3><span class="sp">${u.badge('Dữ liệu: ' + (c.id === 'F01' ? 'impact_truth_F01.json' : 'cause_truth_R01.json'), 'blue', '◇')}</span></div>
      <div class="tbl-wrap"><table class="tbl"><thead><tr><th>Chỉ tiêu</th><th>Tham chiếu</th><th>FlowSight</th><th>Kết quả</th></tr></thead><tbody>${c.rows.map(r => `<tr><td>${r[0]}</td><td>${r[1] ?? '—'}</td><td>${r[2] ?? '—'}</td><td>${r[2] == null ? u.badge('Chưa đủ dữ liệu', 'gray', '?') : ok(r[1], r[2]) ? u.badge('Khớp', 'green', '✔') : u.badge('Lệch', 'red', '✕')}</td></tr>`).join('')}</tbody></table></div>
      <div class="row mt">${Object.entries(c.m).map(([k, v]) => `<div class="card" style="padding:8px 14px"><small>${{ err: 'Sai số (dự báo − thực)', ape: 'APE', p: 'Precision (JT)', r: 'Recall (JT)', hit: 'Top-1 đúng' }[k]}</small><div class="kpi-v" style="font-size:20px">${v == null ? '—' : k === 'err' ? FS.fmt.n(v) : (v * 100).toFixed(0) + '%'}</div></div>`).join('')}</div><small class="muted">${c.note}</small></div>`; }).join('')}
    <div class="card mt"><div class="card-h"><h3>Tham chiếu chất lượng dữ liệu (D01–D04)</h3></div>${Object.keys(dh).length ? u.kv(Object.entries(dh).map(([k, v]) => [k, v && typeof v === 'object' ? Object.entries(v).map(([a, b]) => `${a}: <b>${typeof b === 'object' ? JSON.stringify(b) : b}</b>`).join(' · ') : String(v ?? '—')])) : u.empty('Chưa có dữ liệu tham chiếu chất lượng')}<div class="callout info">Kiểm chứng D01–D04 cần dữ liệu thô có lỗi chèn (raw). Repo hiện chỉ có ground truth sạch → Chưa đủ dữ liệu để so sánh; có thể tải CSV thô ở trang Import & Mapping.</div></div>
    <div class="card mt"><details class="fx"><summary>Định nghĩa chỉ số</summary><ul><li><b>Sai số</b> = dự báo − thực tế · <b>APE</b> = |sai số| / thực tế</li><li><b>Precision</b> = TP / số JT engine báo nguy cơ · <b>Recall</b> = TP / số JT tham chiếu trễ</li><li><b>Top-1</b> = nguyên nhân hàng đầu trùng tham chiếu</li></ul></details>
      <div class="row mt"><button class="btn" id="sv">Lưu phiên bản kiểm chứng</button><small class="muted">Lưu cấu hình ${FS.config.version}, tham số lịch ${FS.config.schedStart}–${FS.config.schedEnd}h, FG ${FS.config.fgUsablePct}%</small></div>
      ${runs.map(r => `<div class="tl"><div><b>${r.t}</b> · ${r.cfg} · F01 sai số ${r.err ?? '—'} · R01 ${r.hit ? 'đúng' : 'lệch'} · dữ liệu: ${r.data}</div></div>`).join('')}</div>`;
    u.$('#sv', root).onclick = () => { runs.unshift({ t: new Date().toISOString().slice(0, 19), cfg: JSON.stringify({ s: FS.config.schedStart, e: FS.config.schedEnd, fg: FS.config.fgUsablePct, rec: FS.config.useRecovery }), err: cases[0].m.err, hit: cases[1].m.hit, data: 'mô phỏng · ' + FS.tables.incident_truth.length + ' sự cố' }); runs.length = Math.min(runs.length, 10); FS.persist.set('valruns', runs); u.toast('Đã lưu phiên bản kiểm chứng'); FS.go(); };
  } };
})();
